### ISSUE TITLE
rk45 and rk4 miss print method

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#308]
When printing a `rk45` or `rk4` no information is provided, especially no information about the allowed settings.
This should be analogue to `cvode` and `gillespie`. Otherwise it is unclear which settings are allowed on the integrator.

```
from __future__ import print_function
import tellurium as te
r = te.loada("""
model m1()
    J0: S1 -> S2; k1*S1;
    S1 = 10.0; S2=0.0;
    k1 = 0.1;
end
""")

print(r.integrator)
r.setIntegrator('gillespie')
print(r.integrator)
r.setIntegrator('rk4')
print(r.integrator)
r.setIntegrator('rk45')
print(r.integrator)
```

```
< roadrunner.Integrator() >
  name: cvode
  settings:
      relative_tolerance: 0.00001
      absolute_tolerance: 0.0000000001
                   stiff: true
       maximum_bdf_order: 5
     maximum_adams_order: 12
       maximum_num_steps: 20000
       maximum_time_step: 0
       minimum_time_step: 0
       initial_time_step: 0
          multiple_steps: false
      variable_step_size: false

< roadrunner.Integrator() >
  name: gillespie
  settings:
                    seed: 1457456997749207
      variable_step_size: false
       initial_time_step: 0
       minimum_time_step: 0
       maximum_time_step: 0
             nonnegative: false

< roadrunner.RK4Integrator() { 'this' : 0x3177da0 }>
< roadrunner.RK45Integrator() { 'this' : 0x3225ad0 }>
```
